### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by matda59** [jancc/vma-extractor#4]
hiya, thanks for this, i get this error  

OS: windows 11 | Python 3.10

c:\temp>vma.py blueiris.vma c:\temp\blueiris
Traceback (most recent call last):
  File "C:\temp\vma.py", line 357, in <module>
    sys.exit(main())
  File "C:\temp\vma.py", line 352, in main
    extract(fo, args)
  File "C:\temp\vma.py", line 243, in extract
    vma_header = VmaHeader(fo, args.skip_hash)
  File "C:\temp\vma.py", line 14, in __init__
    assert magic == b'VMA\0'
AssertionError

**Comment by jancc** [comment]
Huh, wierd. This is literally just the assertion for whether the file you're trying to extract is a valid VMA file (or at least starts with the 4 expected magic bytes). Getting an AssertionError here would just mean that the input file possibly isn't a VMA file. Though arguably the tool's output could be more meaningful.
Are you sure the file you're trying to extract is not compressed or anything?

**Comment by smokedsalmonbagel** [comment]
This happens for me if you use the tool on a lzo file (compressed vma).  I was not able to extract the file in windows had to create a Ubuntu container and use `lzop -d /img/vzdump-qemu-102-2023_08_25-17_33_11.vma.lzo`
